### ISSUE TITLE
function for formatting Dates

### ISSUE THREAD

**Issue by laurianvm** [vliz-be-opsci/pysubyt#31]
include a function that allows to format a date to a given specified format (such as "yyyy-mm-dd")
(e.g. Apr 26 2004 as input to  2004-04-26)

**Comment by marc-portier** [comment]
see https://stackoverflow.com/questions/4830535/how-do-i-format-a-date-in-jinja2 for inspiration

**Comment by laurianvm** [comment]
being handled in py-sema (see: https://github.com/vliz-be-opsci/py-sema/issues/113 & https://github.com/vliz-be-opsci/py-sema/issues/114)
