### ISSUE TITLE
add multiple {--var (-v) NAME VALUE} arguments to the cli for introducing free format key value pairs to be available in the templates

### ISSUE THREAD

**Issue by cedricdcc** [vliz-be-opsci/pysubyt#41]
USECASE:
    I want to use pysubyt with a  template that needs a configurable `{{baseuri}}` to be injected from the CLI.
    This feature should be available via the processor service / interface.
 Approach 
* Capture key, values from cli similar to set , use them to build a dict.
* Allow dict to be passed to `Generator.process`
* Use dict in `JinjaBasedGenerator` to augment the processing context

NOTE 
*Considering possible conflict of already existing keys in the template context
    * Do not prevent but warn end user

**Comment by marc-portier** [comment]
@cedricdcc core of the fix is in place -- can you or @bulricht follow up on (1) some testing to avoid regression in the future and (2) release (+ semver)  to pypi ?

**Comment by bulricht** [comment]
closing this one as there is already an issue for the implementation of tests: https://github.com/vliz-be-opsci/pysubyt/issues/42
